biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

biblioteca/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro', views.cadastro, name='cadastro'),
    path('listar', views.listar, name='listar'),
]

biblioteca/core/models.py
from django.db import models

class LivroModel(models.Model):
    titulo  = models.CharField('Título ', max_length=200)
    editora = models.CharField('Editora', max_length=200)
    autor   = models.CharField('Autor  ', max_length=200)
    isbn    = models.CharField('ISBN   ', max_length=13)
    paginas = models.CharField('Páginas', max_length=3)
    ano     = models.CharField('Ano    ', max_length=4)
    
    def __str__(self):
        return self.titulo
    

biblioteca/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from core.models import LivroModel


def validate_title(value):
    if len(value) < 3:
        raise ValidationError('Deve ter pelo menos TRES caracteres')

def validate_autor(value):
    if len(value) < 10:
        raise ValidationError('Autor deve ter pelo menos DEZ caracteres')
    
def validate_isbn(value):
    if len(value) < 13:
        raise ValidationError('ISBN deve ter TREZE caracteres')
    if not value.isdigit():
        raise ValidationError('ISBN deve ter TREZE caracteres e NUMÉRICOS') 
               
def validate_paginas(value):
    if len(value) < 1:
        raise ValidationError('PÁGINAS deve ter UM a TRES caracteres')
    if not value.isdigit():
        raise ValidationError('PÁGINAS deve ter UM a TRES caracteres e NUMÉRICOS')

def validate_ano(value):
    if len(value) < 4:
        raise ValidationError('ANO deve ter QUATRO caracteres')
    if not value.isdigit():
        raise ValidationError('ANO deve ter QUATRO caracteres e NUMÉRICOS')


class LivroForm(forms.ModelForm):

    class Meta:
        model = LivroModel
        fields = ['titulo', 'editora', 'autor', 'isbn', 'paginas', 'ano']
        error_messages = {
            'titulo': {
                'required': ("Informe o TÍTULO do livro."),
            },
            'editora': {
                'required': ("Informe a EDITORA do livro."),
            },
            'autor': {
                'required': ("Informe o AUTOR do livro."),
            },     
            'isbn': {
                'required': ("Informe o ISBN do livro."),
            },
            'paginas': {
                'required': ("Informe QT PÁGINAS do livro."),
            },
            'ano': {
                'required': ("Informe o ANO do livro."),
            }
        }

    def clean_titulo(self):
        titulo = self.cleaned_data['titulo']
        validate_title(titulo)
        return titulo

    def clean_editora(self):
        editora = self.cleaned_data['editora']
        validate_title(editora)
        return editora
    def clean_autor(self):
        autor = self.cleaned_data['autor']
        validate_autor(autor)
        return autor
    def clean_isbn(self):
        isbn = self.cleaned_data['isbn']
        validate_isbn(isbn)
        return isbn
    def clean_paginas(self):
        paginas = self.cleaned_data['paginas'] 
        validate_paginas(paginas)
        return paginas
    def clean_ano(self):
        ano = self.cleaned_data['ano'] 
        validate_ano(ano)
        return ano  

    def clean(self):
        self.cleaned_data = super().clean()
        return self.cleaned_data


biblioteca/core/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .forms import LivroForm
from .models import LivroModel

def index(request):
    if request.method == 'GET':
        return render(request, "index.html")
    else:
        return HttpResponseRedirect(reverse('core:index'))

def cadastro(request):
    if request.method == 'POST':
        form_livro = LivroForm(request.POST)
        if form_livro.is_valid():
            livro = LivroModel.objects.create(**form_livro.cleaned_data)
            return HttpResponseRedirect(reverse('core:index'))
        else:
            contexto = {'formulario_livro': form_livro}
            return render(request, "cadastro.html", contexto)
    else:
        contexto = {'formulario_livro': LivroForm()}
        return render(request, 'cadastro.html', contexto)

def listar(request):
    if request.method == 'POST':
        livro_id = request.POST.get('livro_id', '')
        try:
            livro = LivroModel.objects.get(pk=livro_id)
            contexto = {'livro': livro}
        except ValueError:
            contexto = {}
        return render(request, "detalhes.html", contexto)
    else:
        livros = LivroModel.objects.all()
        contexto = {'livros': livros}
        return render(request, 'listar.html', contexto)

biblioteca/core/templates/cadastro.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Biblioteca</title>
    </head>
    <body>
            <h1> Biblioteca </h1>
            <h2> Cadastro de Livros </h2>
        <br>

        <form action={% url 'core:cadastro' %} novalidate method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h3>
                {{ formulario_livro.titulo.label }} : {{ formulario_livro.titulo }}
            </h3>
            
            <h3>
                {{ formulario_livro.editora.label }}: {{ formulario_livro.editora }}
            </h3>
            
            <h3>
                {{ formulario_livro.autor.label }}: {{ formulario_livro.autor }}
            </h3>
            
            <h3>
                {{ formulario_livro.isbn.label }}: {{ formulario_livro.isbn}}
            </h3>
            
            <h3>
                {{ formulario_livro.paginas.label }}: {{ formulario_livro.paginas}}
            </h3>
            
            <h3>
                {{ formulario_livro.ano.label }}: {{ formulario_livro.ano}}
            </h3>

            <br>
            <center>
                <input type="submit" value="Cadastrar"/>
            </center>
        </form>
        {% if formulario_livro.errors %}
            {% for field in formulario_livro %}
                {% for error in field.errors %}
                    <strong>{{ error|escape }}</strong><br>
                {% endfor %}
            {% endfor %}
        {% endif %}

        <center>
            <form action={% url 'core:index' %} novalidate method="GET">
                <input type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>

biblioteca/core/templates/detalhes.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Biblioteca</title>
    </head>
    <body>
        <br>
            <h1> Biblioteca </h1>
        <br>

        {% if livro %}
            <h2> Detalhes de um livro selecionado </h2>
            <h3>
                Livro :  {{ livro.titulo }}
                <br>
                Editora : {{ livro.editora }}
                Autor   : {{ livro.autor }}
                Isbn    : {{ livro.isbn}}
                Paginas : {{ livro.paginas}}
                Ano     : {{ livro.ano}}

            </h3>
        <br><br>
        {% else %}
            <h2> Nenhum livro cadastrado </h2>      
        {% endif %} 

        <center>
            <form action={% url 'core:listar' %} novalidate method="GET">
                <input type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>

biblioteca/core/templates/index.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Biblioteca</title>
    </head>
    <body>
        <br>
            <h1> Biblioteca </h1>
            <h2> Sistema para cadastro de livros </h2>
        <br>
        <form action={% url 'core:cadastro' %} novalidate method="GET">
            <input type="submit" value="Cadastrar"/>              
        </form>
        <br>
        <form action={% url 'core:listar' %} novalidate method="GET">
            <input type="submit" value="Listar"/>              
        </form>
    </body>

</html>

biblioteca/core/templates/listar.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Biblioteca</title>
    </head>
    <body>
        <br>
            <h1> Biblioteca </h1>
            <h2> Listar os livros cadastrados </h2>
        <br>

        {% if livros %}
            <h3>Livros Cadastrados</h3>
            {% for livro in livros %}
                <form action={% url 'core:listar' %} novalidate method="POST" enctype="multipart/form-data">
                    {% csrf_token %}        
                    Livro: {{ livro }}
                    <input type="hidden" name="livro_id" value={{ livro.pk }}>        
                    <input type="submit" value="Detalhes"/>              
                </form>
            {% endfor %}
        {% else %}
            <h2> Nenhum livro cadastrado </h2>      
        {% endif %} 

        <center>
            <form action={% url 'core:index' %} novalidate method="GET">
                <input type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>